import { createHash } from "node:crypto";
import { AuthorityHeadStatus, ClaimReleaseStatus } from "./organization-authority-store.js";
import { defineOrganizationWorkContract } from "./organization-work.js";
function invariant(c,m){if(!c) throw new TypeError(m);} function requireText(v,n){invariant(typeof v==="string"&&v.trim(),`${n} must be a non-empty string`);return v;} function freeze(v){return Object.freeze(structuredClone(v));}
function digest(v){return createHash("sha256").update(JSON.stringify(v)).digest("hex");} function releaseKey(id,g){return `${requireText(id,"itemId")}:${g}`;}
function itemFor(board,id){const item=board.items.find(x=>x.id===id);invariant(item,`Blackboard item not found: ${id}`);return item;}
class AuthorityFailure extends Error{constructor(kind,message){super(message);this.kind=kind;}}
function sameObservation(a,b){return a.revision===b.revision&&a.value.generation===b.value.generation&&a.value.artifactRef===b.value.artifactRef;}
async function resolveAuthority({head,resolve,subjectField,subject,kind}){
  if(!head?.value) throw new AuthorityFailure(kind,"authority head unavailable");
  if(head.value.status!==AuthorityHeadStatus.ACTIVE) throw new AuthorityFailure(kind,"authority head is not active");
  const ref=requireText(head.value.artifactRef,"authority artifactRef");
  const artifact=await resolve(ref);
  if(!artifact) throw new AuthorityFailure(kind,`authority artifact not found: ${ref}`);
  if(artifact[subjectField]!==subject||artifact.generation!==head.value.generation||artifact.status!==head.value.status) throw new AuthorityFailure(kind,"authority artifact/head mismatch");
  return {head,artifact,artifactRef:ref};
}
async function currentAuthorities({materializationAuthorizationStore,executionAuthorityPolicyStore,artifactRegistry,authorizationId,policyId,principal,contract}){
  const [mh,ph]=await Promise.all([materializationAuthorizationStore.current(authorizationId),executionAuthorityPolicyStore.current(policyId)]);
  const materialization=await resolveAuthority({head:mh,resolve:(r)=>artifactRegistry.resolveMaterializationAuthorization(r),subjectField:"authorizationId",subject:authorizationId,kind:"WORK"});
  const m=materialization.artifact;
  if(m.acceptedDecisionRef!==contract.acceptedDecisionRef||!m.obligationKeys?.includes(contract.obligationKey)||m.owningDomain&&m.owningDomain!==contract.owningDomain||m.workloadType&&m.workloadType!==contract.workloadType) throw new AuthorityFailure("WORK","work contract outside materialization authority");
  const policy=await resolveAuthority({head:ph,resolve:(r)=>artifactRegistry.resolveExecutionAuthorityPolicy(r),subjectField:"policyId",subject:policyId,kind:"EXECUTION"});
  if(!policy.artifact.principalDomains?.[principal]?.includes(contract.owningDomain)) throw new AuthorityFailure("EXECUTION",`principal ${principal} is not authorized for domain ${contract.owningDomain}`);
  return {materialization,policy};
}
function assertSameAuthorities(before,after){if(!sameObservation(before.materialization.head,after.materialization.head)) throw new AuthorityFailure("WORK","materialization authority changed across durable mutation");if(!sameObservation(before.policy.head,after.policy.head)) throw new AuthorityFailure("EXECUTION","execution authority changed across durable mutation");}
function assertBoardContract(item,contract){invariant(item.origin?.kind==="ORGANIZATION_MATERIALIZATION",`Blackboard item ${item.id} is not organization-managed work`);invariant(item.origin.workContractRef===contract.contractRef,`Blackboard item ${item.id} work contract mismatch`);invariant(item.origin.owningDomain===contract.owningDomain,`Blackboard item ${item.id} owning domain mismatch`);}
export function createOrganizationWorkClaimController({orchestrator,materializationAuthorizationStore,executionAuthorityPolicyStore,claimReleaseStore,artifactRegistry}){
  invariant(orchestrator&&typeof orchestrator.readBlackboard==="function"&&typeof orchestrator.claim==="function","claim controller requires ApplicationOrchestrator");
  invariant(artifactRegistry&&typeof artifactRegistry.resolveWorkContract==="function","claim controller requires artifact registry");
  async function resolveContractForItem(itemId){const board=await orchestrator.readBlackboard();const item=itemFor(board,itemId);const ref=requireText(item.origin?.workContractRef,`Blackboard item ${itemId} workContractRef`);const artifact=await artifactRegistry.resolveWorkContract(ref);invariant(artifact,`work contract artifact not found: ${ref}`);const contract=defineOrganizationWorkContract(artifact);invariant(contract.contractRef===ref,`work contract artifact ref mismatch: ${ref}`);return {item,contract};}
  async function fenceRelease(itemId,generation,invalidationRef){const key=releaseKey(itemId,generation);const current=await claimReleaseStore.current(key);if(!current)return null;if(current.value.status===ClaimReleaseStatus.FENCED)return freeze(current.value);const next={...current.value,status:ClaimReleaseStatus.FENCED,fencedByRef:requireText(invalidationRef,"invalidationRef")};if(await claimReleaseStore.compareAndSwap(key,current.revision,next))return freeze(next);const after=await claimReleaseStore.current(key);invariant(after?.value?.status===ClaimReleaseStatus.FENCED,"claim release fencing conflict");return freeze(after.value);}
  async function invalidateForFailure({itemId,owner,generation,error,ref}){const kind=error?.kind==="WORK"?"WORK_AUTHORIZATION_INVALIDATED":"EXECUTION_AUTHORITY_INVALIDATED";await orchestrator.invalidateOrganizationClaim({itemId,expectedOwner:owner,expectedClaimGeneration:generation,kind,invalidationRef:ref});return kind;}
  return Object.freeze({
    async claim({itemId,principal,authorizationId,policyId}){const {item:before,contract}=await resolveContractForItem(itemId);const identity=requireText(principal?.identity,"principal.identity");assertBoardContract(before,contract);const observed=await currentAuthorities({materializationAuthorizationStore,executionAuthorityPolicyStore,artifactRegistry,authorizationId,policyId,principal:identity,contract});const claimed=await orchestrator.claim({itemId,owner:identity});try{const after=await currentAuthorities({materializationAuthorizationStore,executionAuthorityPolicyStore,artifactRegistry,authorizationId,policyId,principal:identity,contract});assertSameAuthorities(observed,after);}catch(error){await invalidateForFailure({itemId,owner:identity,generation:claimed.result.claimGeneration,error,ref:`claim-freshness:${policyId}:${claimed.result.claimGeneration}`});throw error;}return freeze({item:claimed.result,contract,principal:identity,materializationAuthorizationGeneration:observed.materialization.artifact.generation,executionAuthorityPolicyGeneration:observed.policy.artifact.generation,released:false});},
    async release({itemId,claimGeneration,principal,authorizationId,policyId}){invariant(Number.isInteger(claimGeneration)&&claimGeneration>0,"claimGeneration must be positive");const {contract}=await resolveContractForItem(itemId);const identity=requireText(principal?.identity,"principal.identity");const item=itemFor(await orchestrator.readBlackboard(),itemId);assertBoardContract(item,contract);invariant(item.status==="CLAIMED"&&item.owner===identity&&item.claimGeneration===claimGeneration,"organization claim tuple changed before release");const observed=await currentAuthorities({materializationAuthorizationStore,executionAuthorityPolicyStore,artifactRegistry,authorizationId,policyId,principal:identity,contract});const receipt={kind:"CLAIM_RELEASE_RECEIPT",version:1,itemId,principal:identity,claimGeneration,workContractRef:contract.contractRef,materializationAuthorizationId:authorizationId,materializationAuthorizationRef:observed.materialization.artifactRef,materializationAuthorizationGeneration:observed.materialization.artifact.generation,executionAuthorityPolicyId:policyId,executionAuthorityPolicyRef:observed.policy.artifactRef,executionAuthorityPolicyGeneration:observed.policy.artifact.generation};const receiptRef=`claim-release:sha256:${digest(receipt)}`;const key=releaseKey(itemId,claimGeneration);const current=await claimReleaseStore.current(key);if(current){invariant(current.value.status===ClaimReleaseStatus.RELEASED&&current.value.receiptRef===receiptRef,"conflicting claim release already exists");}else invariant(await claimReleaseStore.compareAndSwap(key,null,{status:ClaimReleaseStatus.RELEASED,receiptRef,receipt}),"conflicting claim release CAS");try{const after=await currentAuthorities({materializationAuthorizationStore,executionAuthorityPolicyStore,artifactRegistry,authorizationId,policyId,principal:identity,contract});assertSameAuthorities(observed,after);}catch(error){const ref=`release-freshness:${receiptRef}`;await invalidateForFailure({itemId,owner:identity,generation:claimGeneration,error,ref});await fenceRelease(itemId,claimGeneration,ref);throw error;}return freeze({...receipt,receiptRef});},
    async assertExecutable({itemId,claimGeneration,receiptRef,authorizationId,policyId}){const current=await claimReleaseStore.current(releaseKey(itemId,claimGeneration));invariant(current?.value?.status===ClaimReleaseStatus.RELEASED&&current.value.receiptRef===receiptRef,"claim release is not current/released");const receipt=current.value.receipt;const item=itemFor(await orchestrator.readBlackboard(),itemId);invariant(item.status==="CLAIMED"&&item.owner===receipt.principal&&item.claimGeneration===claimGeneration,"Board claim tuple no longer matches released capability");const {contract}=await resolveContractForItem(itemId);const authority=await currentAuthorities({materializationAuthorizationStore,executionAuthorityPolicyStore,artifactRegistry,authorizationId,policyId,principal:receipt.principal,contract});invariant(authority.materialization.artifactRef===receipt.materializationAuthorizationRef&&authority.materialization.artifact.generation===receipt.materializationAuthorizationGeneration,"materialization authorization head changed");invariant(authority.policy.artifactRef===receipt.executionAuthorityPolicyRef&&authority.policy.artifact.generation===receipt.executionAuthorityPolicyGeneration,"execution authority policy head changed");return true;},
    async recoverClaim({itemId,principal,authorizationId,policyId,reason}){const {contract}=await resolveContractForItem(itemId);const identity=requireText(principal?.identity,"principal.identity");const before=itemFor(await orchestrator.readBlackboard(),itemId);invariant(before.status==="CLAIMED","organization claim must be CLAIMED before recovery");await currentAuthorities({materializationAuthorizationStore,executionAuthorityPolicyStore,artifactRegistry,authorizationId,policyId,principal:identity,contract});const recovered=await orchestrator.recoverClaim({itemId,owner:identity,reason:requireText(reason,"reason")});await fenceRelease(itemId,before.claimGeneration,`claim-recovery:${recovered.result.claimGeneration}`);return freeze({item:recovered.result,contract,released:false});},
    async invalidateOrganizationClaim({itemId,expectedOwner,expectedClaimGeneration,kind,invalidationRef}){const current=itemFor(await orchestrator.readBlackboard(),itemId);let item;if(current.status==="CLAIMED"){item=(await orchestrator.invalidateOrganizationClaim({itemId,expectedOwner,expectedClaimGeneration,kind,invalidationRef})).result;}else{const expectedStatus=kind==="WORK_AUTHORIZATION_INVALIDATED"?"BLOCKED":"REOPENED";invariant(current.status===expectedStatus&&current.owner==null&&current.claimGeneration===expectedClaimGeneration&&current.evidenceRefs.includes(invalidationRef),"organization invalidation replay mismatch");item=current;}await fenceRelease(itemId,expectedClaimGeneration,invalidationRef);return freeze(item);}
  });
}
